//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsAppointment
    {
        public int Appid { get; set; }
        public string Name { get; set; }
        public string time { get; set; }
        public string Dat { get; set; }
        public string category { get; set; }
        public string mobileno { get; set; }
    }
}
