//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasAgency
    {
        public int Gno { get; set; }
        public string Gname { get; set; }
        public string Email { get; set; }
        public long Phnno { get; set; }
        public string gasagen { get; set; }
        public string address { get; set; }
        public string applydate { get; set; }
    }
}
