//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class guard
    {
        public int SN { get; set; }
        public string Name { get; set; }
        public string blockno { get; set; }
        public long Contact { get; set; }
        public string Checkin { get; set; }
        public string Checkout { get; set; }
    }
}
