//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESocietyDBEntities : DbContext
    {
        public ESocietyDBEntities()
            : base("name=ESocietyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SocietyMemberInfo> SocietyMemberInfoes { get; set; }
        public DbSet<ServiceProvider> ServiceProviders { get; set; }
        public DbSet<BusinessOutlet> BusinessOutlets { get; set; }
        public DbSet<GasAgency> GasAgencies { get; set; }
        public DbSet<DoctorsAppointment> DoctorsAppointments { get; set; }
        public DbSet<ServiceAppoint> ServiceAppoints { get; set; }
        public DbSet<guard> guards { get; set; }
    }
}
