//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public string Service { get; set; }
        public string Availablity { get; set; }
        public long Charges { get; set; }
        public string Description { get; set; }
        public string OpeningTime { get; set; }
        public string ClosingTime { get; set; }
        public int SPID { get; set; }
    }
}
