//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyMemberInfo
    {
        public int SMID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public long ContactNumber { get; set; }
        public string AccountType { get; set; }
        public string HouseNo { get; set; }
        public string BusinessName { get; set; }
        public Nullable<long> Rent { get; set; }
    }
}
